---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maas-workloads
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: maas-workloads
  destination:
    name: in-cluster
    namespace: openshift-gitops
  source:
    path: applications/clusters/example.cluster.opentlc.com/workloads
    repoURL: https://github.com/javo8a/rhoai-workloads.git
    targetRevision: main
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
