---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llmisvc
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: maas-workloads
  destination:
    name: in-cluster
    namespace: ai-models
  source:
    repoURL: https://github.com/javo8a/rhoai-workloads.git
    targetRevision: main
    path: charts/llmisvc
    helm:
      valueFiles:
        - ../../clusters/cluster-8h7g4.8h7g4.sandbox966.opentlc.com/values/llmisvc/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
